import requests
from colr import color

version = "2.83"
enablePrivateLogging = True
hide_names = False
hide_levels = False


gamemodes = {
    "newmap": "New Map",
    "competitive": "Competitive",
    "unrated": "Unrated",
    "swiftplay": "Swiftplay",
    "spikerush": "Spike Rush",
    "deathmatch": "Deathmatch",
    "ggteam": "Escalation",
    "onefa": "Replication",
    "hurm": "Team Deathmatch",
    "custom": "Custom",
    "snowball": "Snowball Fight",
    "": "Custom",
}

before_ascendant_seasons = [
    "0df5adb9-4dcb-6899-1306-3e9860661dd3",
    "3f61c772-4560-cd3f-5d3f-a7ab5abda6b3",
    "0530b9c4-4980-f2ee-df5d-09864cd00542",
    "46ea6166-4573-1128-9cea-60a15640059b",
    "fcf2c8f4-4324-e50b-2e23-718e4a3ab046",
    "97b6e739-44cc-ffa7-49ad-398ba502ceb0",
    "ab57ef51-4e59-da91-cc8d-51a5a2b9b8ff",
    "52e9749a-429b-7060-99fe-4595426a0cf7",
    "71c81c67-4fae-ceb1-844c-aab2bb8710fa",
    "2a27e5d2-4d30-c9e2-b15a-93b8909a442c",
    "4cb622e1-4244-6da3-7276-8daaf1c01be2",
    "a16955a5-4ad0-f761-5e9e-389df1c892fb",
    "97b39124-46ce-8b55-8fd1-7cbf7ffe173f",
    "573f53ac-41a5-3a7d-d9ce-d6a6298e5704",
    "d929bc38-4ab6-7da4-94f0-ee84f8ac141e",
    "3e47230a-463c-a301-eb7d-67bb60357d4f",
    "808202d6-4f2b-a8ff-1feb-b3a0590ad79f",
]
sockets = {
    "skin": "bcef87d6-209b-46c6-8b19-fbe40bd95abc",
    "skin_level": "e7c63390-eda7-46e0-bb7a-a6abdacd2433",
    "skin_chroma": "3ad1b2b2-acdb-4524-852f-954a76ddae0a",
    "skin_buddy": "77258665-71d1-4623-bc72-44db9bd5b3b3",
    "skin_buddy_level": "dd3bf334-87f3-40bd-b043-682a57a8dc3a"
}



AGENTCOLORLIST = {
    "none": (100, 100, 100),
    "astra": (113, 42, 232),
    "breach": (217, 122, 46),
    "brimstone": (217, 122, 46),
    "cypher": (245, 240, 230),
    "chamber": (200, 200, 200),
    "deadlock": (102, 119, 176),
    "fade": (92, 92, 94),
    "jett": (154, 222, 255),
    "kay/o": (133, 146, 156),
    "killjoy": (255, 217, 31),
    "omen": (71, 80, 143),
    "phoenix": (254, 130, 102),
    "raze": (217, 122, 46),
    "reyna": (181, 101, 181),
    "sage": (90, 230, 213),
    "skye": (192, 230, 158),
    "sova": (37, 143, 204),
    "neon": (28, 69, 161),
    "viper": (48, 186, 135),
    "yoru": (52, 76, 207),
    "harbor": (0, 128, 128),
    "gekko": (60, 179, 113),
    "vyse": (97, 83, 183),
    "iso": (154, 222, 255),
    "clove": (191, 158, 227),
    "tejo": (255, 183, 97),
}


GAMEPODS = {
    "aresqa.aws-rclusterprod-use1-1.dev1-gp-ashburn-1": "Ashburn",
    "aresqa.aws-use1-dev.main1-gp-ashburn-1": "Ashburn",
    "aresriot.aws-mes1-prod.eu-gp-bahrain-1": "Bahrain",
    "aresriot.aws-mes1-prod.ext1-gp-bahrain-1": "Bahrain",
    "aresriot.aws-mes1-prod.ext2-gp-bahrain-1": "Bahrain",
    "aresriot.aws-mes1-prod.tournament-gp-bahrain-1": "Bahrain",
    "aresriot.aws-rclusterprod-mes1-1.eu-gp-bahrain-awsedge-1": "Bahrain",
    "aresriot.aws-rclusterprod-mes1-1.ext1-gp-bahrain-awsedge-1": "Bahrain",
    "aresriot.aws-rclusterprod-mes1-1.tournament-gp-bahrain-awsedge-1": "Bahrain",
    "loltencent.qcloud.val-gp-beijing-1": "Beijing",
    "aresriot.aws-bog1-prod.latam-gp-bogota-1": "Bogotá",
    "aresriot.aws-bog1-prod.tournament-gp-bogota-1": "Bogotá",
    "aresriot.aws-rclusterprod-usw2-1.tournament-gp-cmob-1": "CMOB 1",
    "aresriot.aws-rclusterprod-usw2-1.tournament-gp-cmob-2": "CMOB 2",
    "aresriot.aws-rclusterprod-usw2-1.tournament-gp-cmob-3": "CMOB 3",
    "aresriot.aws-rclusterprod-usw2-1.tournament-gp-cmob-4": "CMOB 4",
    "aresriot.aws-afs1-prod.eu-gp-capetown-1": "Cape Town",
    "aresriot.aws-afs1-prod.ext1-gp-capetown-1": "Cape Town",
    "aresriot.aws-afs1-prod.tournament-gp-capetown-1": "Cape Town",
    "aresriot.aws-chi1-prod.ext1-gp-chicago-1": "Chicago",
    "aresriot.aws-chi1-prod.ext2-gp-chicago-1": "Chicago",
    "aresriot.aws-chi1-prod.latam-gp-chicago-1": "Chicago",
    "aresriot.aws-ord1-prod.ext1-gp-chicago-1": "Chicago",
    "aresriot.aws-ord1-prod.latam-gp-chicago-1": "Chicago",
    "aresriot.mtl-riot-ord2-3.ext1-gp-chicago-1": "Chicago",
    "aresriot.mtl-riot-ord2-3.latam-gp-chicago-1": "Chicago",
    "loltencent.qcloud.val-gp-chongqing-1": "Chongqing",
    "arestencent.qcloud-cq1.alpha1-gp-1": "Chongqing 1",
    "arestencent.qcloud-cq1.alpha1-gp-3": "Chongqing 1",
    "arestencent.qcloud-cq1.alpha1-gp-2": "Chongqing 2",
    "arestencent.qcloud-cq1.alpha1-gp-4": "Chongqing 2",
    "arestencent.qcloud-cq1.alpha1-gp-5": "Chongqing 5",
    "arestencent.qcloud-cq1.alpha1-gp-6": "Chongqing 6",
    "arestencent.qcloud-cq1.alpha1-gp-7": "Chongqing 7",
    "arestencent.qcloud-cq1.alpha1-gp-8": "Chongqing 8",
    "aresqa.aws-dfw1-dev.main1-gp-dallas-1": "Dallas",
    "aresqa.aws-rclusterprod-dfw1-1.dev1-gp-dallas-1": "Dallas",
    "aresriot.aws-dfw1-dev.main-gp-dallas-1": "Dallas",
    "aresriot.aws-mec1-prod.eu-gp-dubai-1": "Dubai",
    "aresriot.aws-mec1-prod.tournament-gp-dubai-1": "Dubai",
    "arespreprod.aws-euc1-prod.stage-release-1-gp-frankfurt-1": "Frankfurt",
    "arespreprod.aws-euc1-prod.stage2-gp-frankfurt-1": "Frankfurt",
    "aresqa.aws-euc1-dev.main1-gp-frankfurt-1": "Frankfurt",
    "aresqa.aws-euc1-dev.stage1-gp-frankfurt-1": "Frankfurt",
    "aresqa.aws-rclusterprod-euc1-1.dev1-gp-frankfurt-1": "Frankfurt",
    "aresqa.aws-rclusterprod-euc1-1.stage1-gp-frankfurt-1": "Frankfurt",
    "aresriot.aws-euc1-prod.eu-gp-frankfurt-1": "Frankfurt",
    "aresriot.aws-euc1-prod.ext1-gp-eu1": "Frankfurt",
    "aresriot.aws-euc1-prod.ext1-gp-frankfurt-1": "Frankfurt",
    "aresriot.aws-euc1-prod.ext2-gp-frankfurt-1": "Frankfurt",
    "aresriot.aws-euc1-prod.tournament-gp-frankfurt-1": "Frankfurt",
    "aresriot.aws-rclusterprod-euc1-1.ext1-gp-eu1": "Frankfurt",
    "aresriot.aws-rclusterprod-euc1-1.tournament-gp-frankfurt-1": "Frankfurt",
    "aresriot.aws-rclusterprod-euc1-1.eu-gp-frankfurt-1": "Frankfurt 1",
    "aresriot.aws-rclusterprod-euc1-1.eu-gp-frankfurt-awsedge-1": "Frankfurt 2",
    "aresqa.aws-atl1-dev.main1-gp-atlanta-1": "Georgia",
    "loltencent.qcloud.val-gp-guangzhou-1": "Guangzhou",
    "arestencent.qcloud-gz1.alpha1-gp-1": "Guangzhou 1",
    "arestencent.qcloud-gz1.alpha1-gp-3": "Guangzhou 1",
    "arestencent.qcloud-gz1.alpha1-gp-2": "Guangzhou 2",
    "arestencent.qcloud-gz1.alpha1-gp-4": "Guangzhou 2",
    "arestencent.qcloud-gz1.alpha1-gp-5": "Guangzhou 5",
    "arestencent.qcloud-gz1.alpha1-gp-6": "Guangzhou 6",
    "arestencent.qcloud-gz1.alpha1-gp-7": "Guangzhou 7",
    "arestencent.qcloud-gz1.alpha1-gp-8": "Guangzhou 8",
    "aresriot.aws-ape1-prod.ap-gp-hongkong-1": "Hong Kong",
    "aresriot.aws-ape1-prod.ext1-gp-hongkong-1": "Hong Kong",
    "aresriot.aws-ape1-prod.ext2-gp-hongkong-1": "Hong Kong",
    "aresriot.aws-ape1-prod.tournament-gp-hongkong-1": "Hong Kong",
    "aresriot.aws-rclusterprod-ape1-1.ext1-gp-hongkong-1": "Hong Kong",
    "aresriot.aws-rclusterprod-ape1-1.tournament-gp-hongkong-1": "Hong Kong",
    "aresriot.aws-rclusterprod-ape1-1.ap-gp-hongkong-1": "Hong Kong 1",
    "aresriot.aws-rclusterprod-ape1-1.ap-gp-hongkong-awsedge-1": "Hong Kong 2",
    "aresriot.aws-ist1-prod.eu-gp-istanbul-1": "Istanbul",
    "aresriot.aws-ist1-prod.tournament-gp-istanbul-1": "Istanbul",
    "aresriot.mtl-riot-ist1-2.eu-gp-istanbul-2": "Istanbul",
    "aresriot.mtl-riot-ist1-2.tournament-gp-istanbul-1": "Istanbul",
    "aresriot.mtl-riot-ist1-2.tournament-gp-istanbul-2": "Istanbul",
    "aresriot.mtl-riot-ist1-2.eu-gp-istanbul-1": "Istanbul 2",
    "arespreprod.aws-euw2-prod.cert-gp-london-1": "London",
    "aresriot.aws-euw2-prod.eu-gp-london-1": "London",
    "aresriot.aws-euw2-prod.tournament-gp-london-1": "London",
    "aresriot.aws-rclusterprod-euw2-1.eu-gp-london-awsedge-1": "London",
    "aresriot.aws-rclusterprod-euw2-1.tournament-gp-london-awsedge-1": "London",
    "aresriot.aws-eus2-prod.eu-gp-madrid-1": "Madrid",
    "aresriot.aws-eus2-prod.tournament-gp-madrid-1": "Madrid",
    "aresriot.aws-rclusterprod-mad1-1.eu-gp-madrid-1": "Madrid",
    "aresriot.aws-rclusterprod-mad1-1.tournament-gp-madrid-1": "Madrid",
    "aresriot.aws-qro1-prod.ext1-gp-mexico-1": "Mexico City",
    "aresriot.aws-qro1-prod.ext2-gp-mexico-1": "Mexico City",
    "aresriot.aws-qro1-prod.latam-gp-mexico-1": "Mexico City",
    "aresriot.aws-qro1-prod.tournament-gp-mexico-1": "Mexico City",
    "aresriot.mtl-tmx-mex1-1.ext1-gp-mexicocity-1": "Mexico City",
    "aresriot.mtl-tmx-mex1-1.latam-gp-mexicocity-1": "Mexico City",
    "aresriot.mtl-tmx-mex1-1.tournament-gp-mexicocity-1": "Mexico City",
    "aresriot.aws-mia1-prod.latam-gp-miami-1": "Miami",
    "aresriot.aws-mia1-prod.tournament-gp-miami-1": "Miami",
    "aresriot.aws-mia2-prod.latam-gp-miami-2": "Miami",
    "aresriot.mia1.latam-gp-miami-1": "Miami",
    "aresriot.mia1.tournament-gp-miami-1": "Miami",
    "aresriot.aws-aps1-prod.ap-gp-mumbai-1": "Mumbai",
    "aresriot.aws-aps1-prod.tournament-gp-mumbai-1": "Mumbai",
    "aresriot.aws-rclusterprod-aps1-1.ap-gp-mumbai-awsedge-1": "Mumbai",
    "aresriot.aws-rclusterprod-aps1-1.tournament-gp-mumbai-awsedge-1": "Mumbai",
    "aresqa.aws-rclusterprod-usw1-1.dev1-gp-1": "N. California",
    "aresqa.aws-usw1-dev.main1-gp-norcal-1": "N. California",
    "arestencentqa.qcloud-nj1.stage1-gp-1": "Nanjing",
    "arestencent.qcloud-nj1.alpha1-gp-1": "Nanjing 1",
    "arestencent.qcloud-nj1.alpha1-gp-2": "Nanjing 2",
    "arestencent.qcloud-nj1.alpha1-gp-4": "Nanjing 2",
    "arestencent.qcloud-nj1.alpha1-gp-5": "Nanjing 5",
    "arestencent.qcloud-nj1.alpha1-gp-6": "Nanjing 6",
    "arestencent.qcloud-nj1.alpha1-gp-7": "Nanjing 7",
    "arestencent.qcloud-nj1.alpha1-gp-8": "Nanjing 8",
    "arestencentqa.qcloud-nj1.loadtest1-gp-2": "Nanjing Loadtest 2",
    "arestencent.qcloud-nj1.alpha1-gp-3": "Nanjing Multi ISP",
    "aresriot.aws-rclusterprod-usw2-1.tournament-gp-offline-1": "Offline 1",
    "aresriot.aws-usw2-prod.tournament-gp-offline-1": "Offline 1",
    "aresriot.aws-usw2-prod.tournament-gp-offline-10": "Offline 10",
    "aresriot.aws-usw2-prod.tournament-gp-offline-11": "Offline 11",
    "aresriot.aws-usw2-prod.tournament-gp-offline-12": "Offline 12",
    "aresriot.aws-usw2-prod.tournament-gp-offline-13": "Offline 13",
    "aresriot.aws-usw2-prod.tournament-gp-offline-14": "Offline 14",
    "aresriot.aws-usw2-prod.tournament-gp-offline-15": "Offline 15",
    "aresriot.aws-usw2-prod.tournament-gp-offline-16": "Offline 16",
    "aresriot.aws-usw2-prod.tournament-gp-offline-17": "Offline 17",
    "aresriot.aws-usw2-prod.tournament-gp-offline-18": "Offline 18",
    "aresriot.aws-usw2-prod.tournament-gp-offline-19": "Offline 19",
    "aresriot.aws-rclusterprod-usw2-1.tournament-gp-offline-2": "Offline 2",
    "aresriot.aws-usw2-prod.tournament-gp-offline-2": "Offline 2",
    "aresriot.aws-usw2-prod.tournament-gp-offline-20": "Offline 20",
    "aresriot.aws-usw2-prod.tournament-gp-offline-21": "Offline 21",
    "aresriot.aws-usw2-prod.tournament-gp-offline-22": "Offline 22",
    "aresriot.aws-usw2-prod.tournament-gp-offline-23": "Offline 23",
    "aresriot.aws-usw2-prod.tournament-gp-offline-24": "Offline 24",
    "aresriot.aws-usw2-prod.tournament-gp-offline-25": "Offline 25",
    "aresriot.aws-usw2-prod.tournament-gp-offline-26": "Offline 26",
    "aresriot.aws-usw2-prod.tournament-gp-offline-27": "Offline 27",
    "aresriot.aws-usw2-prod.tournament-gp-offline-28": "Offline 28",
    "aresriot.aws-usw2-prod.tournament-gp-offline-29": "Offline 29",
    "aresriot.aws-rclusterprod-usw2-1.tournament-gp-offline-3": "Offline 3",
    "aresriot.aws-usw2-prod.tournament-gp-offline-3": "Offline 3",
    "aresriot.aws-usw2-prod.tournament-gp-offline-30": "Offline 30",
    "aresriot.aws-rclusterprod-usw2-1.tournament-gp-offline-4": "Offline 4",
    "aresriot.aws-usw2-prod.tournament-gp-offline-4": "Offline 4",
    "aresriot.aws-rclusterprod-usw2-1.tournament-gp-offline-5": "Offline 5",
    "aresriot.aws-usw2-prod.tournament-gp-offline-5": "Offline 5",
    "aresriot.aws-rclusterprod-usw2-1.tournament-gp-offline-6": "Offline 6",
    "aresriot.aws-usw2-prod.tournament-gp-offline-6": "Offline 6",
    "aresriot.aws-rclusterprod-usw2-1.tournament-gp-offline-7": "Offline 7",
    "aresriot.aws-usw2-prod.tournament-gp-offline-7": "Offline 7",
    "aresriot.aws-rclusterprod-usw2-1.tournament-gp-offline-8": "Offline 8",
    "aresriot.aws-usw2-prod.tournament-gp-offline-8": "Offline 8",
    "aresriot.aws-usw2-prod.tournament-gp-offline-9": "Offline 9",
    "aresriot.aws-euw3-prod.eu-gp-paris-1": "Paris",
    "aresriot.aws-euw3-prod.tournament-gp-paris-1": "Paris",
    "aresriot.aws-rclusterprod-euw3-1.tournament-gp-paris-1": "Paris",
    "aresriot.aws-rclusterprod-euw3-1.eu-gp-paris-1": "Paris 1",
    "aresriot.aws-rclusterprod-euw3-1.eu-gp-paris-awsedge-1": "Paris 2",
    "globaltencent.tcc-tcloudtest-sjc1-1.val-gp-1": "SJC",
    "aresriot.aws-scl1-prod.ext1-gp-santiago-1": "Santiago",
    "aresriot.aws-scl1-prod.ext2-gp-santiago-1": "Santiago",
    "aresriot.aws-scl1-prod.latam-gp-santiago-1": "Santiago",
    "aresriot.aws-scl1-prod.tournament-gp-santiago-1": "Santiago",
    "aresriot.mtl-ctl-scl2-2.ext1-gp-santiago-1": "Santiago",
    "aresriot.mtl-ctl-scl2-2.latam-gp-santiago-1": "Santiago",
    "aresriot.mtl-ctl-scl2-2.tournament-gp-santiago-1": "Santiago",
    "aresriot.aws-rclusterprod-sae1-1.ext1-gp-saopaulo-1": "Sao Paulo",
    "aresriot.aws-rclusterprod-sae1-1.tournament-gp-saopaulo-1": "Sao Paulo",
    "aresriot.aws-sae1-prod.br-gp-saopaulo-1": "Sao Paulo",
    "aresriot.aws-sae1-prod.ext1-gp-saopaulo-1": "Sao Paulo",
    "aresriot.aws-sae1-prod.ext2-gp-saopaulo-1": "Sao Paulo",
    "aresriot.aws-sae1-prod.tournament-gp-saopaulo-1": "Sao Paulo",
    "aresriot.aws-rclusterprod-sae1-1.br-gp-saopaulo-1": "Sao Paulo 1",
    "aresriot.aws-rclusterprod-sae1-1.br-gp-saopaulo-awsedge-1": "Sao Paulo 2",
    "arespreprod.aws-apne2-prod.cert-gp-seoul-1": "Seoul",
    "aresriot.aws-apne2-prod.ext1-gp-seoul-1": "Seoul",
    "aresriot.aws-apne2-prod.ext2-gp-seoul-1": "Seoul",
    "aresriot.aws-apne2-prod.kr-gp-seoul-1": "Seoul",
    "aresriot.aws-apne2-prod.tournament-gp-seoul-1": "Seoul",
    "aresriot.aws-rclusterprod-apne2-1.ext1-gp-seoul-1": "Seoul",
    "aresriot.aws-rclusterprod-apne2-1.tournament-gp-seoul-1": "Seoul",
    "aresriot.aws-rclusterprod-apne2-1.kr-gp-seoul-1": "Seoul 1",
    "loltencent.qcloud.val-gp-shanghai-1": "Shanghai",
    "aresqa.aws-apse1-dev.main1-gp-singapore-1": "Singapore",
    "aresriot.aws-apse1-prod.ap-gp-singapore-1": "Singapore",
    "aresriot.aws-apse1-prod.ext1-gp-singapore-1": "Singapore",
    "aresriot.aws-apse1-prod.ext2-gp-singapore-1": "Singapore",
    "aresriot.aws-apse1-prod.tournament-gp-singapore-1": "Singapore",
    "aresriot.aws-rclusterprod-apse1-1.ext1-gp-singapore-1": "Singapore",
    "aresriot.aws-rclusterprod-apse1-1.tournament-gp-singapore-1": "Singapore",
    "aresriot.aws-rclusterprod-apse1-1.ap-gp-singapore-1": "Singapore 1",
    "aresriot.aws-rclusterprod-apse1-1.ap-gp-singapore-awsedge-1": "Singapore 2",
    "aresriot.aws-eun1-prod.eu-gp-stockholm-1": "Stockholm",
    "aresriot.aws-eun1-prod.tournament-gp-stockholm-1": "Stockholm",
    "aresriot.aws-rclusterprod-eun1-1.tournament-gp-stockholm-1": "Stockholm",
    "aresriot.aws-rclusterprod-eun1-1.eu-gp-stockholm-1": "Stockholm 1",
    "aresriot.aws-rclusterprod-eun1-1.eu-gp-stockholm-awsedge-1": "Stockholm 2",
    "arespreprod.aws-apse2-prod.cert-gp-sydney-1": "Sydney",
    "arespreprod.aws-apse2-prod.stage-release-1-gp-sydney-1": "Sydney",
    "arespreprod.aws-apse2-prod.stage2-gp-sydney-1": "Sydney",
    "aresqa.aws-apse2-dev.main1-gp-sydney-1": "Sydney",
    "aresqa.aws-apse2-dev.stage1-gp-sydney-1": "Sydney",
    "aresriot.aws-apse2-prod.ap-gp-sydney-1": "Sydney",
    "aresriot.aws-apse2-prod.ext1-gp-sydney-1": "Sydney",
    "aresriot.aws-apse2-prod.ext2-gp-sydney-1": "Sydney",
    "aresriot.aws-apse2-prod.tournament-gp-sydney-1": "Sydney",
    "aresriot.aws-rclusterprod-apse2-1.ext1-gp-sydney-1": "Sydney",
    "aresriot.aws-rclusterprod-apse2-1.tournament-gp-sydney-1": "Sydney",
    "aresriot.aws-rclusterprod-apse2-1.ap-gp-sydney-1": "Sydney 1",
    "aresriot.aws-rclusterprod-apse2-1.ap-gp-sydney-awsedge-1": "Sydney 2",
    "arestencentqa.qcloud-tj1.stage1-gp-1": "Tianjin",
    "arestencent.qcloud-tj1.alpha1-gp-1": "Tianjin 1",
    "arestencent.qcloud-tj1.alpha1-gp-3": "Tianjin 1",
    "arestencent.qcloud-tj1.alpha1-gp-2": "Tianjin 2",
    "arestencent.qcloud-tj1.alpha1-gp-4": "Tianjin 2",
    "arestencent.qcloud-tj1.alpha1-gp-5": "Tianjin 5",
    "arestencent.qcloud-tj1.alpha1-gp-6": "Tianjin 6",
    "arestencent.qcloud-tj1.alpha1-gp-7": "Tianjin 7",
    "arestencent.qcloud-tj1.alpha1-gp-8": "Tianjin 8",
    "aresriot.aws-apne1-prod.ap-gp-tokyo-1": "Tokyo",
    "aresriot.aws-apne1-prod.eu-gp-tokyo-1": "Tokyo",
    "aresriot.aws-apne1-prod.ext1-gp-kr1": "Tokyo",
    "aresriot.aws-apne1-prod.ext1-gp-tokyo-1": "Tokyo",
    "aresriot.aws-apne1-prod.ext2-gp-tokyo-1": "Tokyo",
    "aresriot.aws-apne1-prod.tournament-gp-tokyo-1": "Tokyo",
    "aresriot.aws-rclusterprod-apne1-1.eu-gp-tokyo-1": "Tokyo",
    "aresriot.aws-rclusterprod-apne1-1.ext1-gp-kr1": "Tokyo",
    "aresriot.aws-rclusterprod-apne1-1.tournament-gp-tokyo-1": "Tokyo",
    "aresriot.aws-rclusterprod-apne1-1.ap-gp-tokyo-1": "Tokyo 1",
    "aresriot.aws-rclusterprod-apne1-1.ap-gp-tokyo-awsedge-1": "Tokyo 2",
    "aresqa.aws-usw2-dev.main1-gp-tournament-2": "Tournament",
    "aresriot.aws-rclusterprod-atl1-1.na-gp-atlanta-1": "US Central (Georgia 2)",
    "aresriot.aws-atl1-prod.na-gp-atlanta-1": "US Central (Georgia)",
    "aresriot.aws-atl1-prod.tournament-gp-atlanta-1": "US Central (Georgia)",
    "aresriot.aws-atl2-prod.na-gp-atlanta-2": "US Central (Georgia)",
    "aresriot.aws-rclusterprod-atl1-1.tournament-gp-atlanta-1": "US Central (Georgia)",
    "aresriot.aws-chi1-prod.na-gp-chicago-1": "US Central (Illinois)",
    "aresriot.aws-chi1-prod.tournament-gp-chicago-1": "US Central (Illinois)",
    "aresriot.aws-chi2-prod.na-gp-chicago-2": "US Central (Illinois)",
    "aresriot.aws-ord1-prod.na-gp-chicago-1": "US Central (Illinois)",
    "aresriot.aws-ord1-prod.tournament-gp-chicago-1": "US Central (Illinois)",
    "aresriot.mtl-riot-ord2-3.na-gp-chicago-1": "US Central (Illinois)",
    "aresriot.mtl-riot-ord2-3.tournament-gp-chicago-1": "US Central (Illinois)",
    "aresriot.aws-dfw1-prod.na-gp-dallas-1": "US Central (Texas)",
    "aresriot.aws-dfw1-prod.tournament-gp-dallas-1": "US Central (Texas)",
    "aresriot.aws-dfw2-prod.na-gp-dallas-2": "US Central (Texas)",
    "aresriot.aws-rclusterprod-dfw1-1.na-gp-dallas-1": "US Central (Texas)",
    "aresriot.aws-rclusterprod-dfw1-1.tournament-gp-dallas-1": "US Central (Texas)",
    "aresriot.aws-rclusterprod-use1-1.na-gp-ashburn-1": "US East (N. Virginia 1)",
    "aresriot.aws-rclusterprod-use1-1.na-gp-ashburn-awsedge-1": "US East (N. Virginia 2)",
    "aresriot.aws-rclusterprod-use1-1.ext1-gp-ashburn-1": "US East (N. Virginia)",
    "aresriot.aws-rclusterprod-use1-1.pbe-gp-ashburn-1": "US East (N. Virginia)",
    "aresriot.aws-rclusterprod-use1-1.tournament-gp-ashburn-1": "US East (N. Virginia)",
    "aresriot.aws-use1-prod.ext1-gp-ashburn-1": "US East (N. Virginia)",
    "aresriot.aws-use1-prod.ext2-gp-ashburn-1": "US East (N. Virginia)",
    "aresriot.aws-use1-prod.na-gp-ashburn-1": "US East (N. Virginia)",
    "aresriot.aws-use1-prod.pbe-gp-ashburn-1": "US East (N. Virginia)",
    "aresriot.aws-use1-prod.tournament-gp-ashburn-1": "US East (N. Virginia)",
    "aresqa.aws-usw2-dev.sandbox1-gp-1": "US West",
    "aresriot.aws-rclusterprod-usw1-1.na-gp-norcal-1": "US West (N. California 1)",
    "aresriot.aws-rclusterprod-usw1-1.na-gp-norcal-awsedge-1": "US West (N. California 2)",
    "arespreprod.aws-usw1-prod.cert-gp-norcal-1": "US West (N. California)",
    "aresriot.aws-rclusterprod-usw1-1.ext1-gp-na2": "US West (N. California)",
    "aresriot.aws-rclusterprod-usw1-1.pbe-gp-norcal-1": "US West (N. California)",
    "aresriot.aws-rclusterprod-usw1-1.tournament-gp-norcal-1": "US West (N. California)",
    "aresriot.aws-usw1-prod.ext1-gp-na2": "US West (N. California)",
    "aresriot.aws-usw1-prod.ext1-gp-norcal-1": "US West (N. California)",
    "aresriot.aws-usw1-prod.ext2-gp-na1": "US West (N. California)",
    "aresriot.aws-usw1-prod.na-gp-norcal-1": "US West (N. California)",
    "aresriot.aws-usw1-prod.pbe-gp-norcal-1": "US West (N. California)",
    "aresriot.aws-usw1-prod.tournament-gp-norcal-1": "US West (N. California)",
    "aresriot.aws-rclusterprod-usw2-1.na-gp-oregon-1": "US West (Oregon 1)",
    "aresriot.aws-rclusterprod-usw2-1.na-gp-oregon-awsedge-1": "US West (Oregon 2)",
    "arespreprod.aws-usw2-prod.stage-release-1-gp-oregon-1": "US West (Oregon)",
    "arespreprod.aws-usw2-prod.stage2-gp-oregon-1": "US West (Oregon)",
    "aresriot.aws-rclusterprod-usw2-1.pbe-gp-oregon-1": "US West (Oregon)",
    "aresriot.aws-rclusterprod-usw2-1.tournament-gp-oregon-1": "US West (Oregon)",
    "aresriot.aws-usw2-prod.na-gp-oregon-1": "US West (Oregon)",
    "aresriot.aws-usw2-prod.pbe-gp-oregon-1": "US West (Oregon)",
    "aresriot.aws-usw2-prod.tournament-gp-oregon-1": "US West (Oregon)",
    "aresqa.aws-usw2-dev.main1-gp-1": "US West 1",
    "aresqa.aws-usw2-dev.stage1-gp-1": "US West 1",
    "globaltencent.tcc-sjc-dev.stage-val-gp-1": "US West 1",
    "globaltencent.tcc-sjc-dev.tcloudtest-stage-release-1-gp-1": "US West 1",
    "globaltencent.tcc-sjc-dev.val-gp-1": "US West 1",
    "aresqa.aws-usw2-dev.main1-gp-4": "US West 2",
    "globaltencent.tcc-sjc-dev.stage-val-gp-2": "US West 2",
    "globaltencent.tcc-sjc-dev.tcloudtest-stage-release-1-gp-2": "US West 2",
    "globaltencent.tcc-sjc-dev.val-gp-2": "US West 2",
    "aresriot.aws-rclusterprod-waw1-1.eu-gp-warsaw-1": "Warsaw",
    "aresriot.aws-rclusterprod-waw1-1.tournament-gp-warsaw-1": "Warsaw",
    "aresriot.aws-waw1-prod.eu-gp-warsaw-1": "Warsaw",
    "aresriot.aws-waw1-prod.tournament-gp-warsaw-1": "Warsaw",
    "tj.qcloud.vala-gp-3": "offline1",
    "tj.qcloud.valtest-gp-3": "offline1",
    "tj.qcloud.vala-gp-4": "offline2",
    "tj.qcloud.valtest-gp-4": "offline2",
    "tj.qcloud.vala-gp-1": "online1",
    "tj.qcloud.valtest-gp-1": "online1",
    "tj.qcloud.vala-gp-2": "online2",
    "tj.qcloud.valtest-gp-2": "online2"
}

symbol = "■"
PARTYICONLIST = [
            color(symbol, fore=(227, 67, 67)),
            color(symbol, fore=(216, 67, 227)),
            color(symbol, fore=(67, 70, 227)),
            color(symbol, fore=(67, 227, 208)),
            color(symbol, fore=(94, 227, 67)),
            color(symbol, fore=(226, 237, 57)),
            color(symbol, fore=(212, 82, 207)),
            symbol
        ]


NUMBERTORANKS = [
            color('Unranked', fore=(46, 46, 46)),
            color('Unranked', fore=(46, 46, 46)),
            color('Unranked', fore=(46, 46, 46)),
            color('Iron 1', fore=(72, 69, 62)),
            color('Iron 2', fore=(72, 69, 62)),
            color('Iron 3', fore=(72, 69, 62)),
            color('Bronze 1', fore=(187, 143, 90)),
            color('Bronze 2', fore=(187, 143, 90)),
            color('Bronze 3', fore=(187, 143, 90)),
            color('Silver 1', fore=(174, 178, 178)),
            color('Silver 2', fore=(174, 178, 178)),
            color('Silver 3', fore=(174, 178, 178)),
            color('Gold 1', fore=(197, 186, 63)),
            color('Gold 2', fore=(197, 186, 63)),
            color('Gold 3', fore=(197, 186, 63)),
            color('Platinum 1', fore=(24, 167, 185)),
            color('Platinum 2', fore=(24, 167, 185)),
            color('Platinum 3', fore=(24, 167, 185)),
            color('Diamond 1', fore=(216, 100, 199)),
            color('Diamond 2', fore=(216, 100, 199)),
            color('Diamond 3', fore=(216, 100, 199)),
            color('Ascendant 1', fore=(24, 148, 82)),
            color('Ascendant 2', fore=(24, 148, 82)),
            color('Ascendant 3', fore=(24, 148, 82)),
            color('Immortal 1', fore=(221, 68, 68)),
            color('Immortal 2', fore=(221, 68, 68)),
            color('Immortal 3', fore=(221, 68, 68)),
            color('Radiant', fore=(255, 253, 205)),
        ]

tierDict = {
            "0cebb8be-46d7-c12a-d306-e9907bfc5a25": (0, 149, 135),
            "e046854e-406c-37f4-6607-19a9ba8426fc": (241, 184, 45),
            "60bca009-4182-7998-dee7-b8a2558dc369": (209, 84, 141),
            "12683d76-48d7-84a3-4e09-6985794f0445": (90, 159, 226),
            "411e4a55-4e59-7757-41f0-86a53f101bb5": (239, 235, 101),
            None: None
        }

WEAPONS = [
    "Classic",
    "Shorty",
    "Frenzy",
    "Ghost",
    "Sheriff",
    "Stinger",
    "Spectre",
    "Bucky",
    "Judge",
    "Bulldog",
    "Guardian",
    "Phantom",
    "Vandal",
    "Marshal",
    "Outlaw",
    "Operator",
    "Ares",
    "Odin",
    "Melee",
]

DEFAULT_CONFIG = {
        "cooldown": 10,
        "port": 1100,
        "weapon": "Vandal",
        "chat_limit": 5,
        "table": {
            "skin": True,
            "rr": True,
            "earned_rr": True,
            "peakrank": True,
            "previousrank" : False,
            "leaderboard": True,
            "headshot_percent": True,
            "winrate": True,
            "kd": False,
            "level": True
        },
        "flags": {
            "last_played": True,
            "auto_hide_leaderboard": True,
            "pre_cls": False,
            "game_chat": True,
            "peak_rank_act": True,
            "discord_rpc": True,
            "aggregate_rank_rr": True
        }
    }
